### ISSUE TITLE
Console hangs?

### ISSUE THREAD

**Issue by milkpirate** [0xFACE/bbconsole#4]
Ok, another thing, the console does not seem to receive something from the device:
```
pi@raspberrypi:~/bbconsole $ ./bbconsole 98:7B:F3:xx:xx:xx
Connecting to.. 98:7B:F3:59:2A:0B
Connected.
PRINT "hello"
RUN
<nothing happens>
```

Shouldnt it print some details? Like here:

[![Foo](https://user-images.githubusercontent.com/9251021/109721996-60968280-7bac-11eb-9ab5-f7261cd4f38d.png)](https://github.com/ozarchie/BlueBasic/wiki/Getting-started:-Hello-World#finally--hello-world)

Maybe some EOL problems? LF vs. CRLF?

And another thing: which image are you using? I found a pretty up to date fork: [kscheff](https://github.com/kscheff/BlueBasic) as well as an little oder one: [fanoush](https://github.com/fanoush/BlueBasic). Any suggestions?

**Comment by ozarchie** [comment]
Hi milkpirate,
I used bbconsole a few years ago to talk to a chinese TI BT CC254x) module.
I used kscheff Bluetooth Basic which derived from https://github.com/aanon4/BlueBasic/wiki/Blue-Basic:-An-Introduction.
I did do some work on it but cannot remember what - https://github.com/ozarchie/BlueBasic-loader.
The updated Wiki which explained it all is somehow lost.

**Comment by milkpirate** [comment]
Hm... too bad. I guess you don't have the hardware handy anymore? And how did you start off with your code (as you mentioned, you're not a C programmer)? Did you use the OSX code as a template? Maybe we could discuss your code some time? Some constructs seem not necessary but I'm far too unfamiliar with the comm. protocol or Bluez to judge that for sure. Also Bluez seems pretty badly documented and I have a rough time understanding what the functions do, which you're calling. Further, do you think it's possible to have that implemented in Python? Because I'm much more familiar with it?

**Comment by 0xFACE** [comment]
This question is probably for me ;-)
The bbcocsole code is borrowed from some tool from the bluez package. The gatttol perhaps?
It basically connects and enables notification for some characteristics and listens for incoming messages.
I never used Python for this, when I started playing with bluetooth LE there wasn't any good Python Bluetooth LE module yet.
I think Python would be better for the development of this tool.

I have some old Chinese HM boards and they still work. Check with a different firmware.
After connecting, bluebasic should display a prompt.

**Comment by milkpirate** [comment]
Yeah sorry, didnt see that it was written by @ozarchie, thanks you! I saw you did it via gatt-tool and a shell script. Will definately look at this as well!

@0xFACE if you still have the programmer available could you dump the firmware for me? Then I would know I have a working device. Right now I am still not sure if its not responding because of me doing something wrong while connecting or the device just behaving different as expected.

**Comment by 0xFACE** [comment]
Take a look at this issue: https://github.com/kscheff/BlueBasic/issues/8

**Comment by milkpirate** [comment]
Ok, now I have some homework 😄 will check all of that!

**Comment by 0xFACE** [comment]
Good luck. There should be something like this when connected:
`Connecting to... xxxxxxxxxxxxxx`
`Connected.`
`BlueBasic CC2541/20150607151946/OAD v0.6`
`http://blog.xojs.org/bluebasic`
`6084 bytes free.`
`OK`

**Comment by milkpirate** [comment]
Ok, read https://github.com/kscheff/BlueBasic/issues/8 and checked the images with my device/rpi/pc.
Sadly none of them worked with the `bbconsole`. This are the results so far (do you spot anything obvious?):

# Original - aanon4 - lastest
https://github.com/aanon4/BlueBasic/blob/c72789766891c1f5584b46b3e5388dd57312af31/hex/BlueBasic-CC2541.hex
```
$ gatttool -I -b 98:7B:F3:xx:xx:xx
[98:7B:F3:xx:xx:xx][LE]> connect
Attempting to connect to 98:7B:F3:xx:xx:xx
Error: connect error: Connection refused (111)
[98:7B:F3:xx:xx:xx][LE]>
```

# Fork (of kscheff) that seems recent - wenij 
https://github.com/wenij/BlueBasic/blob/9d1a7b2f3cb9841dac723a6c472705dd5e116b4c/hex/BlueBasic-CC2541.hex
```
$ gatttool -I -b 98:7B:F3:xx:xx:xx
[98:7B:F3:xx:xx:xx][LE]> connect
Attempting to connect to 98:7B:F3:xx:xx:xx
Error: connect error: Connection refused (111)
[98:7B:F3:xx:xx:xx][LE]>
```

# Fork (of kscheff) that a little older - fanoush 
https://github.com/fanoush/BlueBasic/blob/728992f59c3c298aa300ca750f7af6cd6982a073/hex/BlueBasic-CC2541.hex

**Note**: you mentioned a missing UUID in the thread with kscheff: `25fb9e91-1616-448d-b5a3-f70a64bda73a`. It seems missing her as well :/

```
[98:7B:F3:xx:xx:xx][LE]> connect
Attempting to connect to 98:7B:F3:xx:xx:xx (takes a quite a while...)
Connection successful
[98:7B:F3:xx:xx:xx][LE]> primary
attr handle: 0x0001, end grp handle: 0x000b uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle: 0x000c, end grp handle: 0x000f uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle: 0x0010, end grp handle: 0x0018 uuid: f000ffc0-0451-4000-b000-000000000000
attr handle: 0x0019, end grp handle: 0xffff uuid: 0000180a-0000-1000-8000-00805f9b34fb
[98:7B:F3:xx:xx:xx][LE]> char-desc
handle: 0x0001, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x0002, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0004, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0005, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0006, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0007, uuid: 00002a02-0000-1000-8000-00805f9b34fb
handle: 0x0008, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0009, uuid: 00002a03-0000-1000-8000-00805f9b34fb
handle: 0x000a, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x000b, uuid: 00002a04-0000-1000-8000-00805f9b34fb
handle: 0x000c, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x000d, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x000e, uuid: 00002a05-0000-1000-8000-00805f9b34fb
handle: 0x000f, uuid: 00002902-0000-1000-8000-00805f9b34fb
handle: 0x0010, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x0011, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0012, uuid: f000ffc1-0451-4000-b000-000000000000
handle: 0x0013, uuid: 00002902-0000-1000-8000-00805f9b34fb
handle: 0x0014, uuid: 00002901-0000-1000-8000-00805f9b34fb
handle: 0x0015, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0016, uuid: f000ffc2-0451-4000-b000-000000000000
handle: 0x0017, uuid: 00002902-0000-1000-8000-00805f9b34fb
handle: 0x0018, uuid: 00002901-0000-1000-8000-00805f9b34fb
handle: 0x0019, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x001a, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x001b, uuid: 00002a23-0000-1000-8000-00805f9b34fb
handle: 0x001c, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x001d, uuid: 00002a24-0000-1000-8000-00805f9b34fb
handle: 0x001e, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x001f, uuid: 00002a25-0000-1000-8000-00805f9b34fb
handle: 0x0020, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0021, uuid: 00002a26-0000-1000-8000-00805f9b34fb
handle: 0x0022, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0023, uuid: 00002a27-0000-1000-8000-00805f9b34fb
handle: 0x0024, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0025, uuid: 00002a28-0000-1000-8000-00805f9b34fb
handle: 0x0026, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0027, uuid: 00002a29-0000-1000-8000-00805f9b34fb
handle: 0x0028, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0029, uuid: 00002a2a-0000-1000-8000-00805f9b34fb
handle: 0x002a, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x002b, uuid: 00002a50-0000-1000-8000-00805f9b34fb
[98:7B:F3:xx:xx:xx][LE]> characteristics
handle: 0x0002, char properties: 0x02, char value handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0004, char properties: 0x02, char value handle: 0x0005, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0006, char properties: 0x02, char value handle: 0x0007, uuid: 00002a02-0000-1000-8000-00805f9b34fb
handle: 0x0008, char properties: 0x08, char value handle: 0x0009, uuid: 00002a03-0000-1000-8000-00805f9b34fb
handle: 0x000a, char properties: 0x02, char value handle: 0x000b, uuid: 00002a04-0000-1000-8000-00805f9b34fb
handle: 0x000d, char properties: 0x20, char value handle: 0x000e, uuid: 00002a05-0000-1000-8000-00805f9b34fb
handle: 0x0011, char properties: 0x1c, char value handle: 0x0012, uuid: f000ffc1-0451-4000-b000-000000000000
handle: 0x0015, char properties: 0x1c, char value handle: 0x0016, uuid: f000ffc2-0451-4000-b000-000000000000
handle: 0x001a, char properties: 0x02, char value handle: 0x001b, uuid: 00002a23-0000-1000-8000-00805f9b34fb
handle: 0x001c, char properties: 0x02, char value handle: 0x001d, uuid: 00002a24-0000-1000-8000-00805f9b34fb
handle: 0x001e, char properties: 0x02, char value handle: 0x001f, uuid: 00002a25-0000-1000-8000-00805f9b34fb
handle: 0x0020, char properties: 0x02, char value handle: 0x0021, uuid: 00002a26-0000-1000-8000-00805f9b34fb
handle: 0x0022, char properties: 0x02, char value handle: 0x0023, uuid: 00002a27-0000-1000-8000-00805f9b34fb
handle: 0x0024, char properties: 0x02, char value handle: 0x0025, uuid: 00002a28-0000-1000-8000-00805f9b34fb
handle: 0x0026, char properties: 0x02, char value handle: 0x0027, uuid: 00002a29-0000-1000-8000-00805f9b34fb
handle: 0x0028, char properties: 0x02, char value handle: 0x0029, uuid: 00002a2a-0000-1000-8000-00805f9b34fb
handle: 0x002a, char properties: 0x02, char value handle: 0x002b, uuid: 00002a50-0000-1000-8000-00805f9b34fb
```

# kscheff's images from
https://github.com/kscheff/BlueBasic/tree/ba3374443ccb1d1c817d9d848178cd4a1588a5c6/hex

## BlueBasic-BlueBattery.hex
`Error: connect error: Connection refused (111)`


## BlueBasic-BBX.hex

**Note**: the UUID `25fb9e91-1616-448d-b5a3-f70a64bda73a` is there but with another handle. I tried replacing `0x0031` with `0xffff` but that did not work out :/

```
[98:7B:F3:xx:xx:xx][LE]> primary
attr handle: 0x0001, end grp handle: 0x000b uuid: 00001800-0000-1000-8000-00805f9b34fb
attr handle: 0x000c, end grp handle: 0x000f uuid: 00001801-0000-1000-8000-00805f9b34fb
attr handle: 0x0010, end grp handle: 0x001a uuid: 0000180a-0000-1000-8000-00805f9b34fb
attr handle: 0x001b, end grp handle: 0xffff uuid: 25fb9e91-1616-448d-b5a3-f70a64bda73a
[98:7B:F3:xx:xx:xx][LE]> char-desc
handle: 0x0001, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x0002, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0004, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0005, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0006, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0007, uuid: 00002a02-0000-1000-8000-00805f9b34fb
handle: 0x0008, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0009, uuid: 00002a03-0000-1000-8000-00805f9b34fb
handle: 0x000a, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x000b, uuid: 00002a04-0000-1000-8000-00805f9b34fb
handle: 0x000c, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x000d, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x000e, uuid: 00002a05-0000-1000-8000-00805f9b34fb
handle: 0x000f, uuid: 00002902-0000-1000-8000-00805f9b34fb
handle: 0x0010, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x0011, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0012, uuid: 00002a23-0000-1000-8000-00805f9b34fb
handle: 0x0013, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0014, uuid: 00002a24-0000-1000-8000-00805f9b34fb
handle: 0x0015, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0016, uuid: 00002a26-0000-1000-8000-00805f9b34fb
handle: 0x0017, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0018, uuid: 00002a29-0000-1000-8000-00805f9b34fb
handle: 0x0019, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x001a, uuid: 00002a50-0000-1000-8000-00805f9b34fb
handle: 0x001b, uuid: 00002800-0000-1000-8000-00805f9b34fb
handle: 0x001c, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x001d, uuid: c3fbc9e2-676b-9fb5-3749-2f471dcf07b2
handle: 0x001e, uuid: 00002902-0000-1000-8000-00805f9b34fb
handle: 0x001f, uuid: 00002901-0000-1000-8000-00805f9b34fb
handle: 0x0020, uuid: 00002803-0000-1000-8000-00805f9b34fb
handle: 0x0021, uuid: d6af9b3c-fe92-1cb2-f74b-7afb7de57e6d
handle: 0x0022, uuid: 00002902-0000-1000-8000-00805f9b34fb
handle: 0x0023, uuid: 00002901-0000-1000-8000-00805f9b34fb
[98:7B:F3:xx:xx:xx][LE]> characteristics
handle: 0x0002, char properties: 0x02, char value handle: 0x0003, uuid: 00002a00-0000-1000-8000-00805f9b34fb
handle: 0x0004, char properties: 0x02, char value handle: 0x0005, uuid: 00002a01-0000-1000-8000-00805f9b34fb
handle: 0x0006, char properties: 0x02, char value handle: 0x0007, uuid: 00002a02-0000-1000-8000-00805f9b34fb
handle: 0x0008, char properties: 0x08, char value handle: 0x0009, uuid: 00002a03-0000-1000-8000-00805f9b34fb
handle: 0x000a, char properties: 0x02, char value handle: 0x000b, uuid: 00002a04-0000-1000-8000-00805f9b34fb
handle: 0x000d, char properties: 0x20, char value handle: 0x000e, uuid: 00002a05-0000-1000-8000-00805f9b34fb
handle: 0x0011, char properties: 0x02, char value handle: 0x0012, uuid: 00002a23-0000-1000-8000-00805f9b34fb
handle: 0x0013, char properties: 0x02, char value handle: 0x0014, uuid: 00002a24-0000-1000-8000-00805f9b34fb
handle: 0x0015, char properties: 0x02, char value handle: 0x0016, uuid: 00002a26-0000-1000-8000-00805f9b34fb
handle: 0x0017, char properties: 0x02, char value handle: 0x0018, uuid: 00002a29-0000-1000-8000-00805f9b34fb
handle: 0x0019, char properties: 0x02, char value handle: 0x001a, uuid: 00002a50-0000-1000-8000-00805f9b34fb
handle: 0x001c, char properties: 0x12, char value handle: 0x001d, uuid: c3fbc9e2-676b-9fb5-3749-2f471dcf07b2
handle: 0x0020, char properties: 0x08, char value handle: 0x0021, uuid: d6af9b3c-fe92-1cb2-f74b-7afb7de57e6d
```

### BlueBasic-BlueBattery-D1.hex, BlueBasic-BlueBattery-MPPT.hex, BlueBasic-BlueSolar.hex, BlueBasic-BlueSteca.hex
Same as `BlueBasic-BlueBattery-D1.hex`.

**Comment by milkpirate** [comment]
Ok, got a little further. Wrote a little script:

```
read_out() {
  local -r mac="$1"
  local handles

  handles="$(seq 1 40)"

  for handle in $handles; do
    local response

    handle="$(printf "0x%04x" "$handle")"
    response="$(gatttool --device="$mac" --char-read --handle="$handle" 2>&1)"
    response="${response//Characteristic value\/descriptor: /}"

    grep -qi "failed" <<< "$response" && continue

    response="$(echo "$response" | xxd -r -p | tr -d '\0')"

    echo "$handle: $response"
  done
}
```
and read the characteristics description:
```
$ read_chars 98:7B:F3:xx:xx:xx
0x0001:
0x0002: *
0x0003: BASIC#0B
0x0004: *
0x0005:
0x0006: *
0x0007:
0x0008: *
0x000a:
        *
0x000b: P��
0x000c:
0x000d:  *
0x000f:
0x0010:

0x0011: #*
0x0012:
        *Y�{�
0x0013: $*
0x0014: BLE-1.5.1.1
0x0015: &*
0x0016: BlueBatt/20210302182944
0x0017: )*
0x0018: blue-battery.com
0x0019: P*
 x001a:
0x001b: :��d
▒▒▒▒D���%
0x001c: ��G/I7��kg����
0x001d:
0x001e:
0x001f: Console in                                <========
0x0020:!m~�}�zK���<���
0x0022:
0x0023: Console out                               <========
```
The corresponding UUIDs is the same `00002901-0000-1000-8000-00805f9b34fb` (I guess it doesnt differ for read and write ops). Anyway, in https://github.com/0xFACE/bbconsole/blob/master/bbconsole.c#L140 ff., https://github.com/0xFACE/bbconsole/blob/master/bbconsole.c#L180 and https://github.com/0xFACE/bbconsole/blob/master/bbconsole.c#L188 you're using 0x0100, 0x002f and 0x0031. Could it suffice to adjust these to the above handles? Which to which?

Another thing, in https://github.com/0xFACE/bbconsole/blob/master/bbconsole.c#L166 you're splitting the line in 10 byte chunks before sending. Is that necessary for the device's receive buffer not to overflow? Is it best practise for BLE? Or is it another reason?

**Comment by 0xFACE** [comment]
Yes, splitting is needed. Probably because of the of the buffer size.

**Comment by milkpirate** [comment]
Hey @0xFACE @ozarchie @kscheff

I found [bleak](https://github.com/hbldh/bleak), a cross platform BLE module (python) and coded something: https://gitlab.com/milkpirate/bbpyc.

Would live to have you having a look and test it on your systems if you like. The magic mostly happens in https://gitlab.com/milkpirate/bbpyc/-/blob/master/bbpyc.py#L88 and https://gitlab.com/milkpirate/bbpyc/-/blob/master/bbpyc.py#L135. 

There are still some problems: https://gitlab.com/milkpirate/bbpyc#todo you might have an idea to solve them?

**Comment by kscheff** [comment]
I see the upload is in 10 byte chunks. The iOS and MacOS version of the console are sending up to 19 bytes, but as soon as a `\n` is discovered it will send the buffer even if its below the 19 bytes limit. See details here: https://github.com/kscheff/BlueBasic/blob/master/Console/osx/BlueBasicConsole/BlueBasicOSX/Uploader.swift#L59
and here for the BLE write
https://github.com/kscheff/BlueBasic/blob/master/Console/osx/BlueBasicConsole/BlueBasicOSX/Console.swift#L182

I have currently no access to a Linux or Windows machine with BLE attached for testing - have to see how the macOS Version might perform.

☀️Kai
PS for the purpose of uploading files and keeping the memory clean, I usually use `//` for annotations in the program. These comments are not uploaded, thus speeding up the task.

**Comment by kscheff** [comment]
This is how the console comes up under iOS with the current BlueBasic-BlueBattery build:
https://user-images.githubusercontent.com/8903302/110541062-87623500-8127-11eb-885f-b8fccca158f5.mov

This is how the performance of the macOS console (real time):
https://user-images.githubusercontent.com/8903302/110542362-3d7a4e80-8129-11eb-86b3-8439273c1bc1.mov

**Comment by milkpirate** [comment]
@kscheff :D I guess it performs pretty badly 😄 I asked just to know if its working, but since: https://github.com/hbldh/bleak/blob/f47f32fbeae06f895992f7537874f23a3e2f1ea6/examples/scanner.py#L20 it might not even does that.

**Comment by kscheff** [comment]
https://github.com/hbldh/bleak/blob/f47f32fbeae06f895992f7537874f23a3e2f1ea6/examples/scanner.py#L20
This is not a device address, it's a _private_  specific UUID and changes from system to system, even for the same device with the same physical Bluetooth address. So this hack it kind of ugly.

**Comment by 0xFACE** [comment]
I started to develop the Blue Basic console using the native bluetooth web API. I have uploaded early code on Firebase here: https://webbluebasic.web.app/. 
This should work at least for Chrome on Windows and Android.
Feel free to check if it working for you.
The code is not ready for publishing, these are my first attempts.
I am curious if it will discover and connect BlueBasic devices.

**Comment by kscheff** [comment]
can't get the webbluetooth running on my M1 Mac under Chrome. I have been successful with other  webbluetooth connection in this combination. The scan window stays empty :-(

When I use this app https://atc1441.github.io/TelinkFlasher.html I get all my Bluetooth Devices listed when hitting connect.

**Comment by 0xFACE** [comment]
When I call the API, it allows certain parameters to be passed to filter BLE devices in discovery windows.
I suppose that might be a problem.
I have those parameters hard coded:

```
  blueBasic: {
    primaryService: '25fb9e91-1616-448d-b5a3-f70a64bda73a',
    notifyCharacteristic: 'c3fbc9e2-676b-9fb5-3749-2f471dcf07b2',
    writeCharacteristic: 'd6af9b3c-fe92-1cb2-f74b-7afb7de57e6d'
  }
```
I suppose the primaryService must be the same.

Unfortunately, I do not have a working device at the moment to confirm this.
I'll try to turn off filtering, for debug. Then it will show all devices advertising nearby.

**Comment by kscheff** [comment]
When filtering the device would need to send all this in the advertising or scan packet. Usually this is not the case for the characteristics. Only the primary service should be present, but this is also not always the case. Typically the devices sends a name, you may consider manually filtering for names (like BlueBasic*), but then the BlueBasic program can alter that name and then you are out of luck. So I would suggest not to filter like that.

**Comment by 0xFACE** [comment]
You're right.
Originally I used this code to communicate with the OBD2 diagnostic interfaces.
Those OBD2 interfaces advertised this data.

Deployed new version, without filtering.

**Comment by kscheff** [comment]
OK, now I get connection:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/8903302/154489655-8540d69c-6f95-4fa2-97c1-b55647dd4155.png">

The List button also works:
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/8903302/154489968-09b2065c-b80e-402f-94c7-129d141daaa9.png">

Also Stop and Run are responding correctly. However interactive commands do not show a result. I often use the command interface for debuting (printing content of variables) or use interactive commands to manipulate pins, etc.

The initial prompt message after connection gets truncated, but running a program shows correct output:
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/8903302/154490936-b25af751-74c9-47e7-9c5b-1530053fb4f8.png">

**Comment by 0xFACE** [comment]
Thanks for the confirmation, good to know it works for you.
Interactive commands have not yet been implemented. 
How is it done in the console for Apple ios? Works like a full screen editor?
